baseURL: "https://noahpeeters.de"
title: "Noah Peeters"
theme: "zzo"

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
hasCJKLanguage: true

summaryLength: 70
buildFuture: true

copyright: "&copy;2019 -- {year}, All Rights Reserved"
timeout: 10000
enableEmoji: true
paginate: 13
rssLimit: 100

enableGitInfo: true
googleAnalytics: ""

markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: true
  highlight:
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2

outputs:
  home: ["HTML", "RSS", "SearchIndex"]
  section: ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm: ["HTML", "RSS", "SearchIndex"]
  taxonomy: ["HTML", "RSS", "SearchIndex"]

mediaTypes:
  text/X-podcast:
    suffixes:
      - rss

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "index"
    isPlainText: true
    notAlternative: true
  Podcast:
    mediaType: "text/X-podcast"
    basename: "feed"
    isPlainText: true
    notAlternative: false
    permalinkable: true
    isHTML: true

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"
