logoText: Noah Peeters
logoType: "short" # long, short
description: "Homepage of Noah Peeters"
custom_css:
  - scss/forms.scss
custom_js: []
useFaviconGenerator: true # https://www.favicon-generator.org/
meta_image: ""
themecolor: ""

themeOptions: ["light", "dark", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome: ["contact", "talks", "about", "projects", "publication", "presentation", "resume", "calendar"]
notAllowedTypesInHomeSidebar: ["about", "archive", "projects", "publication", "presentation", "resume", "calendar"]
notAllowedTypesInArchive: ["about", "contact", "talks", "projects", "publication", "presentation", "resume", "calendar"]
notAllowedTypesInHomeFeed: ["about", "archive", "contact", "talks", "projects", "publication", "presentation", "resume", "gallery", "calendar"]

viewportSize: "normal" # widest, wider, wide, normal, narrow
enableUiAnimation: true
hideSingleContentsWhenJSDisabled: false
enablePinnedPosts: true
minItemsToShowInTagCloud: 1 # Minimum items to show in tag cloud

# header
homeHeaderType: "text" # text, img, slide

# menu
showMobileMenuTerms: ["tags", "categories", "series"]

# body
enableBreadcrumb: true
enablePhotoSwipe: true
enableSearch: true
enableSearchHighlight: true
enableGoToTop: true
enableWhoami: true
summaryShape: "classic" # card, classic, compact
searchResultPosition: "main" # side, main
archiveGroupByDate: "2006" # "2006-01": group by month, "2006": group by year
archivePaginate: 13
paginateWindow: 1
talksPaginate: 5
talksGroupByDate: "2006"
pubPaginate: 20

# whoami
myname: "Noah Peeters"
email: "noah@noahpeeters.de"
whoami: "🌱 Vegan CS Student and iOS Developer"
bioImageUrl: ""
useGravatar: false
location: "Germany, Geesthacht"
organization: "freenet.de"
link: "https://noahpeeters.de"

# sidebar
enableBio: true
enableBioImage: true
enableSidebar: true
enableSidebarTags: true
enableSidebarSeries: true
enableSidebarCategories: true
enableHomeSidebarTitles: true
enableListSidebarTitles: true
enableToc: true
hideToc: false
tocFolding: true
tocPosition: "inner" # inner, outer
enableTocSwitch: true
itemsPerCategory: 5
sidebarPosition: "right"
tocLevels: ["h2", "h3", "h4"]
enableSidebarPostsByOrder: false

# footer
showPoweredBy: true
showFeedLinks: true
showSocialLinks: true
enableLangChange: false
enableThemeChange: true

# service
googleTagManager: "" # GTM-XXXXXX
baiduAnalytics: ""
enableBusuanzi: false
busuanziSiteUV: true
busuanziSitePV: true
busuanziPagePV: true

# rss
updatePeriod: "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency: ""
fullContents: false

# comment
enableComment: true
disqus_shortname: ""
commento: false

telegram:
  enable: false
  siteId: ""
  dataLimit: 5

gitment:          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner: ""              # Your GitHub ID
  repo: ""               # The repo to store comments
  clientId: ""           # Your client ID
  clientSecret: ""       # Your client secret

utterances:       # https://utteranc.es/
  owner: "NoahPeeters"              # Your GitHub ID
  repo: "noahpeeters.de-comments"               # The repo to store comments

gitalk:           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner: ""              # Your GitHub ID
  repo: ""               # The repo to store comments
  clientId: ""           # Your client ID
  clientSecret: ""       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
valine:
  enable: false
  appId: ""
  appKey: ""
  notify: false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  avatar: 'mm'
  placeholder: '说点什么吧...'
  visitor: false

changyan:
  changyanAppid: ""        # Changyan app id             # 畅言
  changyanAppkey: ""       # Changyan app key

livere:
  livereUID: ""            # LiveRe UID                  # 来必力

# Isso: https://posativ.org/isso/
isso:
  enable: false
  scriptSrc: "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs: "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

socialOptions:
  email: "mailto:noah@noahpeeters.de"
  phone: "tel:+4917642987761"
  facebook: ""
  twitter: "https://twitter.com/noah_peeters"
  github: "https://github.com/NoahPeeters"
  stack-overflow: "https://stackoverflow.com/users/10961090/noah-peeters?tab=profile"
  instagram: ""
  google-plus: ""
  youtube: ""
  medium: ""
  tumblr: ""
  linkedin: "https://www.linkedin.com/in/noahpeeters"
  pinterest: ""
  stack-exchange: "https://stackexchange.com/users/12880236/noah-peeters"
  telegram: "https://t.me/NoahPeeters"
  steam: ""
  weibo: ""
  douban: ""
  csdn: ""
  gitlab: ""
  mastodon: ""
  jianshu: ""
  zhihu: ""
  signal: ""
  whatsapp: "https://wa.me/4917642987761"
  matrix: ""
  xmpp: ""
  dev-to: ""
  gitea: ""
  google-scholar: ""
  orcid: "https://orcid.org/0000-0002-0506-923X"
  xing: "https://www.xing.com/profile/Noah_Peeters"
  keybase: "https://keybase.io/noahpeeters"
  applemusic: "https://music.apple.com/profile/noahpeeters"

donationOptions:
  enable: false
  alipay: ""
  wechat: ""
  paypal: ""
  patreon: ""

# possible share name: ["facebook","twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line"]
share:
  - name: "facebook"
    username: ""
  - name: "twitter"

footerLinks:
  - name: Privacy Policy
    link: /privacy
  - name: Imprint
    link: /imprint
  - name: Digital documents
    link: /digital-documents
